### ISSUE TITLE
I can´t create add my password

### ISSUE THREAD

**Issue by Pablo2m** [a-urth/jbpy#1]
After entering my JID turns red and will not let me put my password

W7 x64 
Python 2.7.4 x64 
Sleekxmpp 1.1.11
Pyside 1.1.2 x64

Here is a screenshot

![JBPY 17042013 071440 p m ](https://f.cloud.github.com/assets/557413/394200/d9fbb5ea-a7b2-11e2-9ed2-18a6d28fcbfa.jpg)

**Comment by a-urth** [comment]
I completely forgot that server part can contain dots. Fixed and commited.
By the way, xmpp.ru... are You from Russia?

**Comment by Pablo2m** [comment]
No, i live in Argentina.  It may seem strange but I liked that server
Thanks for fixing it.
Do you think  support transport soon?

**Comment by a-urth** [comment]
I was thinking about that.
At first i was planning to implement transport of pictures with drag-n-drop.
In future all files, but i'm not sure if SleekXMPP supports transport XEP.
